### ISSUE TITLE
what is the _metainfo.csv files refer to?

### ISSUE THREAD

**Issue by franzt7788** [ZhicengShi/mclSTExp#1]
Hi there, 

Thank you for sharing this interesting work. I am a beginner in this topic and try to follow your work. When ran the hvg_cscc.py, it indicated error information as follows: FileNotFoundError: [Errno 2] No such file or directory: './GSE144240_RAW/P2_ST_rep1_metainfo.csv'. I just curious about what is the P2_ST_rep1_metainfo.csv refers to? Could you upload these files if possible? Thanks.

Best,
Franzt

**Comment by ZhicengShi** [comment]
The ***_metainfo.csv file contains gene expression profile information. The raw dataset includes approximately 1933 spots with expression data. However, according to the spot_data-selection.csv file from the original dataset, only around 666 spots are overlaid on the histological images. Our task is to predict gene expression profiles from histological images, so we retained only the spots that are overlaid on the histological images. The code to generate the metainfo.csv file can be found on line 135 of the dataset.py file and only needs to be run once. Please let us know if you have any questions.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shizhiceng/mclSTExp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月19日(星期五) 晚上6:54
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[shizhiceng/mclSTExp] what is the _metainfo.csv files refer to? (Issue #1)





 
Hi there,
 
Thank you for sharing this interesting work. I am a beginner in this topic and try to follow your work. When ran the hvg_cscc.py, it indicated error information as follows: FileNotFoundError: [Errno 2] No such file or directory: './GSE144240_RAW/P2_ST_rep1_metainfo.csv'. I just curious about what is the P2_ST_rep1_metainfo.csv refers to? Could you upload these files if possible? Thanks.
 
Best,
 Franzt

**Comment by franzt7788** [comment]
Thank you for your prompt and detailed explanations. I got it.
