### ISSUE TITLE
关于10X数据spots_feature维度于position不匹配的

### ISSUE THREAD

**Issue by Hanminghao** [ZhicengShi/mclSTExp#3]
![QQ截图20240912135930](https://github.com/user-attachments/assets/1f375ef9-cf95-44f5-ab90-59023d5fe8ad)
spots_feature维度为685而position维度为785，不匹配无法相加。
请问这个您是如何解决的，似乎代码中并没有对这个进行处理。

**Comment by ZhicengShi** [comment]
不应该呀，图像维度应该是1024然后被投射到256，spots_feature维度为685，position的维度也是685，然后spots_feature+position 再投射到256，position是和spots_feature加起来的
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZhicengShi/mclSTExp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月12日(星期四) 下午2:01
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[ZhicengShi/mclSTExp] 关于10X数据spots_feature维度于image_featrues不匹配的 (Issue #3)





 
QQ.20240912135930.png (view on web)
 spots_feature维度为685而position和image_features维度为768，不匹配无法相加。
 请问这个您是如何解决的，似乎代码中并没有对这个进行处理。

**Comment by Hanminghao** [comment]
对不起，我找到了输入dim的指令，不是您的问题。
