### ISSUE TITLE
1000hvg_common.pkl数据来源

### ISSUE THREAD

**Issue by Hanminghao** [ZhicengShi/mclSTExp#4]
您好，在运行Alex+10x数据集代码时我发现您的论文以及1000hvg_common.pkl中提到筛选出的基因数量为685个，但是我按照您论文中的方法对Alex+10x数据集进行基因筛选得到的结果为3316，请问是否可以提供生成1000hvg_common.pkl的代码呢？
这个是您论文中提供的方法：
![image](https://github.com/user-attachments/assets/f4e209fe-88a7-45dc-8b2d-39970eb891f8)
这个是我进行基因筛选的代码：
![image](https://github.com/user-attachments/assets/64d3dd92-a3fe-40c6-98fc-af42b550ab11)

**Comment by ZhicengShi** [comment]
不好意思，回复晚了，筛选代码你可以查看hvg_visium.py 文件，最后筛选到的基因表达数据在log_transformed_expression中

**Comment by ZhicengShi** [comment]
这个筛选方法的代码是来自Generalization of deep learning models for predicting spatial gene expression profiles using histology images: A breast cancer case study 这篇文章

**Comment by ZhicengShi** [comment]
对不起，回复晚了。1000hvg_common.pkl文件来自2022年Generalization of deep learning models for predicting spatial gene expression profiles using histology images:A breast cancer case study这篇文章，您也可以按照方法自己做筛选，可以筛前3000个高可变，也可以筛前1000个高可变，这是自定义的。
